### ISSUE TITLE
Multiple streams

### ISSUE THREAD

**Issue by bjhiltbrand** [eroji/rtsp2mjpg#1]
Hi, I just cloned this repo and configured the compose file for my Ubiquiti camera I'm using to monitor my 3d printer. I was amazed at how fast I was able to put it together and have it work pretty flawlessly. Well done! I was curious if it was possible to setup the compose file to server multiple streams from different cameras at all, or if I would simply have to create multiple containers, one for each stream? I would like to use mjpg for a number of apps/home automation solutions that don't support rtsp.

Thanks again for this. It works so well, and I'm excited to see what else I can do with it. :)

**Comment by eroji** [comment]
@bjhiltbrand it would most likely the be latter case since you'll need another set of ffmpeg and ffserver instances for each additional cameras. The easiest and quickest way would be to clone the repo into multiple folders of cam1, cam2, cam3 etc and then modify the port mapping for each set so they don't all collide on port 80, then start them up.

**Comment by bjhiltbrand** [comment]
Cool, that's what I was thinking would be the best way, and then I put a reverse proxy in front of these instances so I could use one ingress point. Awesome job again. Thanks!
