### ISSUE TITLE
Past duration 0.979988 too large

### ISSUE THREAD

**Issue by Rubeast** [eroji/rtsp2mjpg#15]
I really love this docker container and it was the missing piece in a project of mine.
But it only keeps working for about a day. When I open the link after that, it page stays loading but nothing is displayed.
When I check the logs I see this:

![image](https://user-images.githubusercontent.com/5304947/103693962-6f8cfa00-4f9a-11eb-821c-1728b1e65c86.png)

**Comment by eroji** [comment]
It's hard to say if that's the root cause of the container stopping after a day. There could be a variety of causes due to the nature of having to transcode video in realtime. However, those entries appears to be caused by ffmpeg. Maybe you can try tweaking the command using info here: https://stackoverflow.com/questions/30782771/what-does-past-duration-x-xxx-too-large-mean.
