### ISSUE TITLE
Stream freezes after ~20 seconds

### ISSUE THREAD

**Issue by korethegenius** [eroji/rtsp2mjpg#6]
Thanks for making this great container! 

I've been having this issue on my Pi 4 and also iMac where the stream runs fine for ~15-20 seconds and then freezes. At the same time, there seems to be huge CPU demand while it's running. Any ideas about the cause?

**Comment by eroji** [comment]
CPU usage is going to be high unfortunately due to the nature of video transcoding. In terms of video stream freezing, it could be a number of things and I cannot say for certain what it is for your setup. You can check and see if the container itself logged any errors. It is possible that ffmpeg process died due to some sort of problem. You may need to tweak the ffserver.conf and ffmpeg command parameters.

**Comment by eroji** [comment]
Looks like there's problem with the source stream. This is something I ran into myself because my wifi network was dropping packets. Video transcoding is very time sensitive. FFmpeg expects the source stream data to arrive as close to realtime as possible and in sequence. If you have packet loss, the packet will need to be resent and will arrive out of sequence. So when FFmpeg is transcoding the frames to mjpeg, it's doing frame 1-2-3-4-5... but the frame arrived as 1-2-??-4-5-3, this will cause it to barf and stop. Disclaimer, I am not an expert on ffmpeg at all, but it is what I found as part of researching into my problem. After I fixed the packet loss (cabling problem) it was far more improved, but wireless camera is nontheless not ideal source feed.
